# Generated by Django 4.2.1 on 2023-06-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='company',
        ),
        migrations.AddField(
            model_name='manager',
            name='enterprise',
            field=models.ManyToManyField(blank=True, related_name='manager', to='enterprise.enterprise'),
        ),
    ]
