# Generated by Django 4.2.1 on 2023-07-25 18:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_buy_datetime'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 18, 2, 53, 250810)),
        ),
        migrations.AlterField(
            model_name='route',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 25, 13, 2, 53, 250786)),
        ),
        migrations.AlterField(
            model_name='route',
            name='vehicle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='vehicle.vehicle'),
        ),
    ]
