# Generated by Django 4.2.1 on 2023-07-04 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='duration',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='start_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
