# Generated by Django 4.2.1 on 2023-07-26 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_alter_route_end_alter_route_start_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 7, 59, 54, 156131)),
        ),
        migrations.AlterField(
            model_name='route',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 2, 59, 54, 156110)),
        ),
    ]
