# Generated by Django 4.2.1 on 2023-07-04 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_buy_datetime'),
        ('route', '0002_route_duration_route_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicle.vehicle'),
        ),
    ]
