# Generated by Django 4.2.1 on 2023-07-26 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_alter_route_end_alter_route_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 8, 36, 48, 734998)),
        ),
        migrations.AlterField(
            model_name='route',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 26, 3, 36, 48, 734977)),
        ),
    ]
