# Generated by Django 4.2.1 on 2023-08-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_alter_route_end_alter_route_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
