# Generated by Django 4.2.1 on 2023-08-05 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_buy_datetime'),
        ('route', '0006_route_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='vehicle.vehicle'),
        ),
    ]
