# Generated by Django 4.2.1 on 2023-07-04 08:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0002_vehicle_buy_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('vehicle', models.ManyToManyField(related_name='point', to='vehicle.vehicle')),
            ],
        ),
    ]
