# Generated by Django 4.2.1 on 2023-07-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
