# Generated by Django 4.2.1 on 2023-07-06 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_buy_datetime'),
        ('point', '0002_point_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='point',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='point',
            name='vehicle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='point', to='vehicle.vehicle'),
            preserve_default=False,
        ),
    ]
