# Generated by Django 4.2.1 on 2023-06-07 19:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_per_hour', models.FloatField()),
                ('total_cost', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('production_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2023)])),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brand.brand')),
                ('enterprise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='enterprise.enterprise')),
            ],
        ),
    ]
