# Generated by Django 4.2.1 on 2023-05-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_per_hour', models.FloatField()),
                ('total_cost', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('production_year', models.DateField()),
            ],
        ),
    ]
