# Generated by Django 4.2.1 on 2023-05-25 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('body_type', models.CharField(choices=[('CARG', 'Cargo'), ('BUS', 'Bus'), ('PICK', 'Pickup'), ('SEDA', 'Sedan'), ('CABR', 'Cabriolet')], default='SEDA', max_length=4)),
                ('tank_capacity', models.IntegerField()),
                ('passanger_seat_count', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='vehicle.brand'),
            preserve_default=False,
        ),
    ]
