# Generated by Django 4.2.1 on 2023-05-29 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
        ('vehicle', '0002_brand_vehicle_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brand.brand'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
