# Generated by Django 4.2.1 on 2023-08-05 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_buy_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='mileage',
        ),
    ]
