# Generated by Django 4.2.1 on 2023-05-30 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('vehicle', '0003_alter_vehicle_brand_delete_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.enterprise'),
        ),
    ]
