# Generated by Django 4.2.1 on 2023-06-07 08:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('vehicle', '0005_rename_company_vehicle_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='enterprise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle', to='enterprise.enterprise'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='production_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1960), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
