# Generated by Django 4.2.1 on 2023-06-07 18:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
        ('vehicle', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('salary', models.IntegerField()),
                ('hire_date', models.DateField(default=datetime.date.today)),
                ('active_vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_driver', to='vehicle.vehicle')),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='enterprise.enterprise')),
                ('vehicle', models.ManyToManyField(blank=True, to='vehicle.vehicle')),
            ],
        ),
    ]
