# Generated by Django 4.2.1 on 2023-05-30 19:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0004_vehicle_company'),
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('salary', models.IntegerField()),
                ('hire_date', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=False)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.enterprise')),
                ('vehicle', models.ManyToManyField(to='vehicle.vehicle')),
            ],
        ),
    ]
