# Generated by Django 4.2.1 on 2023-05-30 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='company',
            new_name='enterprise',
        ),
    ]
