# Generated by Django 4.2.1 on 2023-05-30 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_rename_company_vehicle_enterprise'),
        ('driver', '0002_rename_company_driver_enterprise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='is_active',
        ),
        migrations.AddField(
            model_name='driver',
            name='active_vehicle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_driver', to='vehicle.vehicle'),
        ),
    ]
