# Generated by Django 4.2.1 on 2023-05-30 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('vehicle', '0005_rename_company_vehicle_enterprise'),
        ('driver', '0003_remove_driver_is_active_driver_active_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='active_vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_driver', to='vehicle.vehicle'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enterprise.enterprise'),
        ),
    ]
