# Generated by Django 4.2.1 on 2023-06-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_rename_company_vehicle_enterprise'),
        ('driver', '0004_alter_driver_active_vehicle_alter_driver_enterprise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.ManyToManyField(null=True, to='vehicle.vehicle'),
        ),
    ]
