# Generated by Django 4.2.1 on 2023-06-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_rename_company_vehicle_enterprise'),
        ('driver', '0005_alter_driver_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.ManyToManyField(blank=True, null=True, to='vehicle.vehicle'),
        ),
    ]
