# Generated by Django 4.2.1 on 2023-06-07 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('vehicle', '0005_rename_company_vehicle_enterprise'),
        ('driver', '0006_alter_driver_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='enterprise.enterprise'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle',
            field=models.ManyToManyField(blank=True, to='vehicle.vehicle'),
        ),
    ]
