# Generated by Django 4.2.1 on 2023-05-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('body_type', models.CharField(choices=[('CARG', 'Cargo'), ('BUS', 'Bus'), ('PICK', 'Pickup'), ('SEDA', 'Sedan'), ('CABR', 'Cabriolet')], default='SEDA', max_length=4)),
                ('tank_capacity', models.IntegerField()),
                ('passanger_seat_count', models.IntegerField()),
            ],
        ),
    ]
