# Generated by Django 4.2.1 on 2023-07-26 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle', '0002_vehicle_buy_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start_datetime', models.DateField()),
                ('end_datetime', models.DateField()),
                ('type', models.TextField(editable=False)),
                ('period', models.TextField(choices=[('Дневная', 'Дневная'), ('Месячная', 'Месячная'), ('Годовая', 'Годовая')])),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMileageReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.report')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehicle')),
            ],
            bases=('report.report',),
        ),
        migrations.CreateModel(
            name='MileAgeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('mileage', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.vehiclemileagereport')),
            ],
        ),
    ]
