# Generated by Django 4.2.1 on 2023-07-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyMileage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start_datetime', models.DateField()),
                ('end_datetime', models.DateField()),
                ('period', models.TextField(choices=[('DAY', 'day'), ('MONTH', 'month'), ('YEAR', 'year')])),
                ('type', models.TextField(default='Пробег автомобиля за период', editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
