# Generated by Django 4.2.1 on 2023-07-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start_datetime', models.DateField()),
                ('end_datetime', models.DateField()),
                ('period', models.TextField(choices=[('DAY', 'day'), ('MONTH', 'month'), ('YEAR', 'year')])),
            ],
        ),
        migrations.DeleteModel(
            name='MonthlyMileage',
        ),
        migrations.CreateModel(
            name='VehicleMileageReport',
            fields=[
                ('abstractreport_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='report.abstractreport')),
                ('type', models.TextField(default='Пробег автомобиля за период', editable=False)),
            ],
            bases=('report.abstractreport',),
        ),
    ]
