# Generated by Django 4.2.1 on 2023-07-26 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_abstractreport_delete_monthlymileage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('value', models.IntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.vehiclemileagereport')),
            ],
        ),
    ]
